// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAagDm0uHVxo_SEZDdsyjsOGJBHTkA3eAc',
    appId: '1:444674696388:web:e946f0cd1a19f06d98d591',
    messagingSenderId: '444674696388',
    projectId: 'attendance-tracking-syst-3384a',
    authDomain: 'attendance-tracking-syst-3384a.firebaseapp.com',
    storageBucket: 'attendance-tracking-syst-3384a.appspot.com',
    measurementId: 'G-NC8TSTD469',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMvRT4ZAaCTozTJqyl-2PAMQBwVDB7w5I',
    appId: '1:444674696388:android:2be97a7b328e1a0c98d591',
    messagingSenderId: '444674696388',
    projectId: 'attendance-tracking-syst-3384a',
    storageBucket: 'attendance-tracking-syst-3384a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzNCSBCefGLtroh3Gf73uKO-mNkSUUrcM',
    appId: '1:444674696388:ios:1808c3b29c38177998d591',
    messagingSenderId: '444674696388',
    projectId: 'attendance-tracking-syst-3384a',
    storageBucket: 'attendance-tracking-syst-3384a.appspot.com',
    iosBundleId: 'com.example.bizalysInfosystemAssesment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzNCSBCefGLtroh3Gf73uKO-mNkSUUrcM',
    appId: '1:444674696388:ios:1808c3b29c38177998d591',
    messagingSenderId: '444674696388',
    projectId: 'attendance-tracking-syst-3384a',
    storageBucket: 'attendance-tracking-syst-3384a.appspot.com',
    iosBundleId: 'com.example.bizalysInfosystemAssesment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAagDm0uHVxo_SEZDdsyjsOGJBHTkA3eAc',
    appId: '1:444674696388:web:2de6c646a906c94a98d591',
    messagingSenderId: '444674696388',
    projectId: 'attendance-tracking-syst-3384a',
    authDomain: 'attendance-tracking-syst-3384a.firebaseapp.com',
    storageBucket: 'attendance-tracking-syst-3384a.appspot.com',
    measurementId: 'G-5NGB418ZCW',
  );
}
